name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main   # Run only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial!
      pages: write
      id-token: write

    steps:
      # Step 1: Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
      # Step 3: Build Flutter Web
      - name: Build Web
        run: flutter build web --release --base-href /portfolio/ 

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
